// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBuildLog(arg1:string):Promise<Array<string>>;

export function LoadConf():Promise<string>;

export function MergeConf(arg1:string):Promise<boolean>;

export function OpenProject(arg1:string):Promise<void>;

export function OpenTarsReleaseFile():Promise<string>;

export function RunRelease(arg1:string):Promise<void>;

export function RunReleaseBeforeBuild(arg1:string,arg2:string):Promise<string>;
