// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBuildLog(arg1) {
  return window['go']['apis']['App']['CheckBuildLog'](arg1);
}

export function LoadConf() {
  return window['go']['apis']['App']['LoadConf']();
}

export function MergeConf(arg1) {
  return window['go']['apis']['App']['MergeConf'](arg1);
}

export function OpenTarsReleaseFile() {
  return window['go']['apis']['App']['OpenTarsReleaseFile']();
}

export function RunRelease(arg1) {
  return window['go']['apis']['App']['RunRelease'](arg1);
}

export function RunReleaseBeforeBuild(arg1, arg2) {
  return window['go']['apis']['App']['RunReleaseBeforeBuild'](arg1, arg2);
}
